Feat: Slack Bot Tool
phidatahq/phidata pull request #1261
Opened 2024-10-17 18:06 UTC by manthanguptaa

2024-10-17 18:40 UTC, anuragts commented
LGTM

2024-10-17 20:28 UTC, ashpreetbedi requested changes
Really, really good PR. Just requested small changes to the structure but everything else looks perfect

2024-10-17 20:28 UTC, ashpreetbedi commented on phi/tools/slack.py
> +
wrap in try/except Import error. see: https://github.com/phidatahq/phidata/blob/main/phi/tools/duckdb.py#L6-L9

2024-10-17 20:28 UTC, ashpreetbedi commented on phi/tools/slack.py
> +        self.register(self.get_channel_history)
wrap in variables eg:

if send_message:
    ...
    
see: https://github.com/phidatahq/phidata/blob/main/phi/tools/duckdb.py#L36-L45

2024-10-18 11:01 UTC, ashpreetbedi approved these changes

2024-10-18 11:02 UTC, merged