feat: update firecrawl tool with additional features
phidatahq/phidata pull request #1445
Opened 2024-11-14 12:45 UTC by AbhishekRP2002

- fresh clean PR aiming to close #1349 
- Previous closed PR for ref: #1357 

cc: @manthanguptaa

2024-11-18 04:26 UTC, AbhishekRP2002 commented
@manthanguptaa  any updates on this ?

2024-11-19 09:08 UTC, manthanguptaa commented
Ran into this issue while running the code

![Screenshot 2024-11-19 at 2 38 18 PM](https://github.com/user-attachments/assets/830e80c7-0f81-40fa-9a3c-d77c77928cb9)

2024-11-19 09:08 UTC, manthanguptaa commented on cookbook/tools/firecrawl_tools.py
> +    agent.print_response(f"Crawl and analyze the main use cases and  insights using asynchronous crawling: {url}")
extra whitespace in the middle of the sentence

2024-11-19 09:11 UTC, manthanguptaa commented on cookbook/tools/firecrawl_tools.py
Can you not have Agents in functions and then call them? I think you can have only 1 Agent with the following config
```
Agent(
        tools=[FirecrawlTools(scrape=True, crawl=True, async_crawl=True, limit=25)],
        show_tool_calls=True,
        reasoning=True,
        markdown=True,
    )
```
and then ask the agent to do it synchronously or asynchronously

2024-11-19 09:16 UTC, manthanguptaa commented on phi/tools/firecrawl.py
> +            self.register(self.cancel_crawl)
async crawl cannot be cancelled?

2024-11-19 14:28 UTC, AbhishekRP2002 commented on phi/tools/firecrawl.py
> +            self.register(self.check_crawl_status)
if only `async_crawl` is True then also the code block will execute @manthanguptaa

2024-11-19 14:53 UTC, AbhishekRP2002 commented
> Ran into this issue while running the code
> 
> ![Screenshot 2024-11-19 at 2 38 18 PM](https://private-user-images.githubusercontent.com/42516515/387575766-830e80c7-0f81-40fa-9a3c-d77c77928cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjQ2NTAsIm5iZiI6MTczMjAyNDM1MCwicGF0aCI6Ii80MjUxNjUxNS8zODc1NzU3NjYtODMwZTgwYzctMGY4MS00MGZhLTlhM2MtZDc3Yzc3OTI4Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEzNTIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYzY3Y2FkZjkzMjZmOTJmZTI3YTY5ZjhiZWE0YjU4MTJiYmRkOGJiMDM2Y2Q2ZjQ3NjdiMzk0NzZlNGExZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mi2_er2huyt12t9bxMYkKk8mDOUXVrbYEQvAMAdE004)

@manthanguptaa  did u encounter it while running the cookbook script ?
what is the openai model being used by default ?
This is most likely due to stochastic nature of the llm model, as a result of which it could parse the exact tool params . I wasn't able to reproduce it. 

PFA for ref:
![image](https://github.com/user-attachments/assets/fdb185cd-f8de-4194-9b91-177bf3199054)
![image](https://github.com/user-attachments/assets/41e5d6e3-3c01-42b7-92fd-9f5e834bbddc)
![image](https://github.com/user-attachments/assets/b3b6dd5f-3194-46a9-87ec-c8e3345c2b04)
![image](https://github.com/user-attachments/assets/588df849-2828-4a34-9620-28f6c5083eaf)

2024-12-06 19:39 UTC, AbhishekRP2002 commented
Hi @manthanguptaa any updates on this ? Please lemme know if there's refactoring that needs to be done.

2024-12-20 05:29 UTC, manthanguptaa requested changes

2024-12-30 09:10 UTC, manthanguptaa commented
Took this to completion in #1659

2024-12-30 09:10 UTC, closed without merging