Add MongoDB support [VectorDB]
phidatahq/phidata pull request #1505
Opened 2024-12-03 07:04 UTC by ranfysvalle02

Potentially closes https://github.com/phidatahq/phidata/pull/1412

Add MongoDB as a VectorDB.

2024-12-05 14:49 UTC, manthanguptaa commented
@ranfysvalle02 we don't want the MDBVector class in the cookbook

2024-12-08 15:16 UTC, ranfysvalle02 commented
@manthanguptaa I will clean this up shortly, still a 'Work in Progress'. Will update here once ready! Sorry for the delay

2024-12-09 05:32 UTC, ranfysvalle02 commented
@manthanguptaa now its ready for review! thanks for your patience! Basic RAG is now working 

![phidata-0](https://github.com/user-attachments/assets/483e33d3-bc1a-442e-a328-2120a551193f)

2024-12-10 09:55 UTC, manthanguptaa commented
Can you please remove the output from the cookbook? I am reviewing the PR right now

2024-12-10 11:10 UTC, ranfysvalle02 commented
@manthanguptaa will update now! THANK YOU

2024-12-10 11:12 UTC, ranfysvalle02 commented
Output removed @manthanguptaa 

https://github.com/phidatahq/phidata/pull/1505/files/2129259a36b30c58221dbaa8881f5d1d299c149e..84cd173ce06d59c896270e26f23f59cbdb4b454b

2024-12-11 00:37 UTC, ranfysvalle02 commented
@manthanguptaa any other changes you want me to do to get Basic MongoDB RAG support merged?

2024-12-17 15:21 UTC, ranfysvalle02 commented
@manthanguptaa just following up here --- any other changes before we can add MongoDB support?

2024-12-18 13:51 UTC, manthanguptaa commented
@ranfysvalle02 allow me some time to get to this PR to review.

2024-12-18 17:34 UTC, ranfysvalle02 commented
"we don't want the MDBVector class in the cookbook"
--> addressed, I've attached a screenshot.

"Can you please remove the output from the cookbook? I am reviewing the PR right now"
-->addressed, see screenshot.

" But I still see a lot of my comments haven't been addressed. "
--> Can you please specify what I missed? Happy to help get this down the line. I have some availability today to address any remaining issues.

@manthanguptaa

2024-12-18 17:35 UTC, ranfysvalle02 commented
<img width="1361" alt="Screenshot 2024-12-18 at 12 32 01 PM" src="https://github.com/user-attachments/assets/74820722-b0e3-4532-a9d9-217bd523c2f1" />

2024-12-20 05:30 UTC, manthanguptaa requested changes

2024-12-20 08:38 UTC, ranfysvalle02 commented on phi/vectordb/mongodb/mongodb.py
> +class MDBVector(VectorDb):
<img width="1369" alt="Screenshot 2024-12-20 at 3 35 58 AM" src="https://github.com/user-attachments/assets/67f0a3ca-44cd-436d-9d1a-2594ab94c800" />

2024-12-20 08:39 UTC, ranfysvalle02 commented on phi/vectordb/mongodb/mongodb.py
> +class MDBVector(VectorDb):
<img width="1369" alt="Screenshot 2024-12-20 at 3 35 58 AM" src="https://github.com/user-attachments/assets/67f0a3ca-44cd-436d-9d1a-2594ab94c800" />

2024-12-20 08:39 UTC, ranfysvalle02 commented on phi/vectordb/mongodb/mongodb.py
> +class MDBVector(VectorDb):
<img width="1369" alt="Screenshot 2024-12-20 at 3 35 58 AM" src="https://github.com/user-attachments/assets/67f0a3ca-44cd-436d-9d1a-2594ab94c800" />

2024-12-20 08:45 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
> +"""
@manthanguptaa 

I have removed the output. I believe this one has been resolved, see screenshot.
<img width="994" alt="Screenshot 2024-12-20 at 3 42 46 AM" src="https://github.com/user-attachments/assets/4204a507-ecec-40b6-b92d-271533fbc8dd" />

<img width="945" alt="Screenshot 2024-12-20 at 3 33 45 AM" src="https://github.com/user-attachments/assets/dc60a6d7-deb1-4108-a458-c5e2313770af" />

2024-12-20 08:45 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
On it, will report back shortly.

2024-12-20 09:03 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
<img width="1096" alt="Screenshot 2024-12-20 at 4 01 43 AM" src="https://github.com/user-attachments/assets/535135e0-12eb-4ea6-ac10-d1da1b42ca79" />

2024-12-20 09:08 UTC, ranfysvalle02 reviewed
I believe I covered all the feedback. Please propose any remaining changes, I think we are close! Thank you for your patience!

2024-12-21 11:59 UTC, manthanguptaa commented
This looks good @ranfysvalle02! I will be testing hopefully tomorrow

2024-12-21 16:55 UTC, ranfysvalle02 commented
Thank you for your patience and feedback! We're almost there! :)

2024-12-23 14:25 UTC, ranfysvalle02 commented
@manthanguptaa just following up on this --- anything I can do to get this PR merged in soon? :)

2024-12-30 10:03 UTC, manthanguptaa commented on cookbook/vectordb/mongodb.py
> +- connection string will be "mongodb://localhost/?directConnection=true"
Tried following the docker development route but didn't work. Told me that it needs additional functionality to work

2024-12-30 10:03 UTC, manthanguptaa commented on cookbook/vectordb/mongodb.py
> +agent.print_response("How to make Thai curry?", markdown=True)
You can remove this

2024-12-30 10:04 UTC, manthanguptaa commented on cookbook/vectordb/mongodb.py
You need to format this a little. You can take a look at the other vectordb cookbook to see how its formatted. Need a little space between lines

2025-01-05 02:05 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
> +agent.print_response("How to make Thai curry?", markdown=True)
removed.

2025-01-05 02:05 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
Will take a look at others and add some space between the lines 👍

2025-01-05 05:05 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
> +- connection string will be "mongodb://localhost/?directConnection=true"
"Told me that it needs additional functionality to work" -- 

Can you please elaborate a bit more? I was able to get it working with MongoDB Atlas (both cloud and docker);
The code should work smoothly if provided a valid MongoDB URI. I will be changing the wording a bit.... 

```
This script demonstrates how to load knowledge from a PDF document and query it using an agent, with MongoDB Atlas as the vector database.  
To use MongoDB Atlas Vector Search, follow these steps:
1. Sign Up for MongoDB Atlas:
   - Visit the MongoDB Atlas website and sign up for a free account.
2. Create a New Cluster:
   - Log in and click "Build a Cluster".
   - Choose the Free Shared Clusters (M0) option.
   - Select your preferred cloud provider and region.
   - Click "Create Cluster".
3. Configure Network Access:
   - Go to "Network Access" in the left-hand menu.
   - Click "Add IP Address". Make sure you can connect to MongoDB Atlas from your local network.
4. Create a Database User:
   - Navigate to "Database Access" in the left-hand menu.
   - Click "Add New Database User".
   - Choose "Password" as the authentication method.
   - Enter a username and password.
   - Assign "Read and write to any database" role.
   - Click "Add User".
5. Obtain the Database Connection URL:
   - Go to "Clusters" and click "Connect" for your cluster.
   - Select "Connect your application".
   - Choose Python as your driver and select your version.
   - Copy the provided connection string and replace `<username>` and `<password>` with your credentials.

Example connection string:
"mongodb+srv://<username>:<password>@cluster0.mongodb.net/?retryWrites=true&w=majority"

For local development, you can use:
- docker pull mongodb/mongodb-atlas-local
- docker run -p 27017:27017 mongodb/mongodb-atlas-local
- connection string will be "mongodb://localhost/?directConnection=true"
```

This is the most verbose 'instructions' on any of the other databases. Will match the style of the others, including spaces and more concise content. WIll push shortly.

2025-01-05 05:05 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
> +- connection string will be "mongodb://localhost/?directConnection=true"
```
# install pymongo - `pip install pymongo`

from phi.agent import Agent
from phi.knowledge.pdf import PDFUrlKnowledgeBase
import os
#os.environ["OPENAI_API_KEY"] = ""
from phi.vectordb.mongodb import MongoDBVector

# MongoDB Atlas connection string 
"""
Example connection strings:
"mongodb+srv://<username>:<password>@cluster0.mongodb.net/?retryWrites=true&w=majority"
"mongodb://localhost/?directConnection=true"
"""
mdb_connection_string = ""

knowledge_base = PDFUrlKnowledgeBase(
    urls=["https://phi-public.s3.amazonaws.com/recipes/ThaiRecipes.pdf"],
    vector_db=MongoDBVector(collection_name="recipes", db_url=mdb_connection_string, wait_until_index_ready=60, wait_after_insert=300),
) #adjust wait_after_insert and wait_until_index_ready to your needs
knowledge_base.load(recreate=True)  

# Create and use the agent
agent = Agent(knowledge_base=knowledge_base, use_tools=True, show_tool_calls=True)
agent.print_response("How to make Thai curry?", markdown=True)
```

I think this is much better -- let me know what you think.

2025-01-05 05:06 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
```
# install pymongo - `pip install pymongo`

from phi.agent import Agent
from phi.knowledge.pdf import PDFUrlKnowledgeBase
import os
#os.environ["OPENAI_API_KEY"] = ""
from phi.vectordb.mongodb import MongoDBVector

# MongoDB Atlas connection string 
"""
Example connection strings:
"mongodb+srv://<username>:<password>@cluster0.mongodb.net/?retryWrites=true&w=majority"
"mongodb://localhost/?directConnection=true"
"""
mdb_connection_string = ""

knowledge_base = PDFUrlKnowledgeBase(
    urls=["https://phi-public.s3.amazonaws.com/recipes/ThaiRecipes.pdf"],
    vector_db=MongoDBVector(collection_name="recipes", db_url=mdb_connection_string, wait_until_index_ready=60, wait_after_insert=300),
) #adjust wait_after_insert and wait_until_index_ready to your needs
knowledge_base.load(recreate=True)  

# Create and use the agent
agent = Agent(knowledge_base=knowledge_base, use_tools=True, show_tool_calls=True)
agent.print_response("How to make Thai curry?", markdown=True)
```

I think I got it this time! Thanks again for your patience!

2025-01-05 05:07 UTC, ranfysvalle02 commented
@manthanguptaa - Sorry for the delay, I finally got the time to get through this -- I think we are finally going to get MongoDB into phi :) Thanks again for all the feedback and patience!

2025-01-07 06:40 UTC, manthanguptaa commented on cookbook/vectordb/mongodb.py
> +agent = Agent(knowledge_base=knowledge_base, use_tools=True, show_tool_calls=True)
please remove `use_tools=True`

2025-01-07 06:41 UTC, manthanguptaa commented on phi/vectordb/mongodb/mongodb.py
> +import os
Let's order the imports here where 
1. Inbuilt python lib imports
2. Phidata related imports
3. 3rd party imports

We are very close to finishing this off. I have tested the code and its working perfectly

2025-01-07 17:48 UTC, ranfysvalle02 commented on cookbook/vectordb/mongodb.py
> +agent = Agent(knowledge_base=knowledge_base, use_tools=True, show_tool_calls=True)
DONE

```
agent = Agent(knowledge_base=knowledge_base, show_tool_calls=True)
```

2025-01-07 17:56 UTC, ranfysvalle02 commented on phi/vectordb/mongodb/mongodb.py
> +import os
This is what I ended up doing -- 

```
import time
from typing import List, Optional, Dict, Any

from phi.document import Document
from phi.embedder import Embedder
from phi.embedder.openai import OpenAIEmbedder
from phi.vectordb.base import VectorDb
from phi.utils.log import logger
from phi.vectordb.distance import Distance

try:
    from hashlib import md5

except ImportError:
    raise ImportError("`hashlib` not installed. Please install using `pip install hashlib`")
try:
    from pymongo import MongoClient, errors
    from pymongo.operations import SearchIndexModel
    from pymongo.collection import Collection

except ImportError:
    raise ImportError("`pymongo` not installed. Please install using `pip install pymongo`")

class MongoDBVector(VectorDb):
```

I think I got it - but feel free to propose changes/edits or tell me the exact order. We are super close!

2025-01-07 19:12 UTC, ranfysvalle02 commented
@manthanguptaa - I think I got all the feedback. Thanks again!

2025-01-07 19:16 UTC, manthanguptaa approved these changes

2025-01-07 19:16 UTC, merged