Fix: Added instructions for setting DEEPSEEK_API_KEY and restarting e…
phidatahq/phidata pull request #1606
Opened 2024-12-19 11:49 UTC by Shivam909058

This PR resolves issue #1602, where users face an error when trying to use other large models due to missing DEEPSEEK_API_KEY.
- Added instructions in the script to set the DEEPSEEK_API_KEY environment variable.
- Included comments on restarting the environment after setting the API key.

- Follow the steps provided in the comments of the updated script.
- Set the API key using the command prompt or terminal.
- Restart the environment and run the script to verify the fix.

Fixes #1602

2024-12-19 12:58 UTC, manthanguptaa commented
Thanks for your PR @Shivam909058 but this doesn't belong here.

2024-12-19 13:06 UTC, Shivam909058 commented
Also this PR is important LIKE  if someone is doing contribution using the repo or improving something in this 
Now they will not tackle the problem 

At first i think it is really not working for deepseek but after testing i have seen that people may face this problem 
So that's why i put a notice there

2024-12-20 05:38 UTC, manthanguptaa requested changes
Look at `cookbook/providers/deepseek/agents.py` to make this change. This doesn't belong in this file

2024-12-20 10:43 UTC, dirkbrnd commented on cookbook/agents/07_monitoring.py
> +# IMPORTANT: Before running this script, ensure that the (ANY MODEL )API_KEY environment variable is set.
I don't believe this comment belongs here.
this should be a general tutorial on our docs rather.

2024-12-20 10:57 UTC, closed without merging

2024-12-20 10:59 UTC, Shivam909058 reviewed
yeah so please ad this thing on the docs i would be great move for others , so they would not juggling around with these small mistakes