Image to image agent
phidatahq/phidata pull request #1628
Opened 2024-12-24 04:58 UTC by anuragts

## Description

Image to Image agent that uses Fal tools.

## Type of change

Please check the options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Model update
- [ ] Infrastructure change

## Checklist

- [x] My code follows Phidata's style guidelines and best practices
- [x] I have performed a self-review of my code
- [ ] I have added docstrings and comments for complex logic
- [x] My changes generate no new warnings or errors
- [x] I have added cookbook examples for my new addition (if needed)
- [ ] I have updated requirements.txt/pyproject.toml (if needed)
- [x] I have verified my changes in a clean environment

## Additional Notes

Include any deployment notes, performance implications, or other relevant information:

2024-12-30 10:46 UTC, manthanguptaa commented on phi/tools/fal_tools.py
> +        self.image_url = image_url
Why `image_url` isn't a param in `image_to_image` function?

2025-01-02 11:03 UTC, dirkbrnd requested changes

2025-01-02 11:03 UTC, dirkbrnd commented on phi/tools/fal_tools.py
> +            )
This is how we set the images on the agent

2025-01-02 11:03 UTC, dirkbrnd commented on phi/tools/fal_tools.py
> +        Use this function to generate an image from a given image using the Fal AI API.
What do you mean "From a given image". Maybe give a more detailed explanation and a link to their docs please.

2025-01-03 15:01 UTC, dirkbrnd approved these changes

2025-01-03 15:03 UTC, merged