marketing workflow
phidatahq/phidata pull request #1645
Opened 2024-12-27 05:06 UTC by ysolanky

## Description

Personalized marketing workflow cookbook

## Type of change

Please check the options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Model update
- [ ] Infrastructure change

## Checklist

- [ ] My code follows Phidata's style guidelines and best practices
- [ ] I have performed a self-review of my code
- [ ] I have added docstrings and comments for complex logic
- [ ] My changes generate no new warnings or errors
- [ ] I have added cookbook examples for my new addition (if needed)
- [ ] I have updated requirements.txt/pyproject.toml (if needed)
- [ ] I have verified my changes in a clean environment

2025-01-08 08:56 UTC, manthanguptaa requested changes
The workflow isn't giving the intended output

2025-01-09 04:56 UTC, ysolanky commented
@manthanguptaa please test now. Also added steps for clarity

2025-01-13 17:22 UTC, dirkbrnd approved these changes

2025-01-14 04:44 UTC, willemcdejongh approved these changes

2025-01-14 13:54 UTC, merged