Singlestore as vector and storage database.
phidatahq/phidata pull request #75
Opened 2024-02-05 08:05 UTC by vishwajeetdabholkar

Added singlestore as vector and storage database.
Added cookbook for singlestore.
I have added code to add an indexed ANN search as a commented block. can update this when we can create embeddings column with `vector` data type.

2024-02-06 20:55 UTC, ashpreetbedi commented
@vishwajeetdabholkar requested a few changes, also please run `./scripts/format.sh` to make sure formatting/linting passes. Thanks

2024-02-06 20:56 UTC, ashpreetbedi requested changes

2024-02-06 20:56 UTC, ashpreetbedi commented on cookbook/singlestore-vector/README.md
> +## singlestore Assistant
nit: `SingleStore`

2024-02-06 20:56 UTC, ashpreetbedi commented on phi/vectordb/singlestore/__init__.py
> +# from phi.vectordb.singlestore.index import Ivfflat, HNSWFlat
remove commented out import and add new line

2024-02-06 20:56 UTC, ashpreetbedi commented on phi/vectordb/singlestore/s2vectordb.py
> +        # logger.debug("==== Vector DB Optimized ====")
@vishwajeetdabholkar lets remove this code

2024-02-06 21:00 UTC, ashpreetbedi commented on phi/vectordb/singlestore/s2vectordb.py
> +        # logger.debug("==== Vector DB Optimized ====")
@vishwajeetdabholkar is this for when ANN comes out? then maybe we keep it

2024-02-07 08:00 UTC, vishwajeetdabholkar commented
@ashpreetbedi made the requested changes and added formatting. Let me know if any other change is required.

2024-02-08 21:35 UTC, ashpreetbedi approved these changes
LGTM 🚢

2024-02-08 21:35 UTC, merged